version: "3.8"

services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile.prod
    container_name: laravel_prod
    restart: always
    volumes:
      - ./Back/storage:/var/www/html/storage
      # Mount the directory to avoid issues if the file doesn't exist
      - ./Back/database:/var/www/html/database
    networks:
      - app-network

  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    container_name: react_prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # Mount storage to serve uploaded files
      - ./Back/storage/app/public:/var/www/html/storage/app/public
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
